config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :contacts
  get 'home/index'
  resources :posts
  get 'blags/index'
  get 'blags/show'
  get 'blags/new'
  get 'blags/create'
  get 'blags/edit'
  get 'blags/update'
  get 'blags/destroy'
  
  root 'home#index'

  resources :articles
  resources :blags
  resources :users
  get '/users/create', to: 'users#create', as: 'usercrea'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/blag.rb
class Blag < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create 
    @post = Post.find(params[:post_id])
    @post.avatar.attach(params[:avatar])
    redirect_to(post_path(@post))

  
  end 
end

app/controllers/blags_controller.rb
class BlagsController < ApplicationController
  
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
      if @contact.save
        redirect_to root_path
        flash[:success] = "Email enregistré avec succès !"
      else
        redirect_to root_path
      end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC")
    @contact = Contact.new

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def store
    # upload image to cloudinary
    @image = Cloudinary::Uploader.upload(params[:media])
    # create a new post object and save to db
    @post = Post.new({:title => params[:title], :text => params[:text], :author => params[:author],  :media => @image['secure_url']})
    @post.save
    # trigger an event with pusher

    redirect_to('/')
  end


  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :author, :media, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
    User.create(params["gossip_text"])
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
        options = [:hard_wrap, :autolink, :no_intra_emphasis, :fenced_code_blocks  ]
        Markdown.new(text, *options).to_html.html_safe
    end 
end
 

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/avatars_controller_helper.rb
module AvatarsControllerHelper
end

app/helpers/blags_helper.rb
module BlagsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html lang="en">


    <head>


        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon.ico">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">

        <script type="text/javascript" src="jquery-4.4.0.js"></script>


        <title>Fangorn</title>
        <link rel="icon" type="image/x-icon" href="/Users/aimery/Desktop/THP/J5/good/assets/img/Iconsmind-Outline-Tree-22.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->

        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="app/assets/stylesheets/application.scss" rel="stylesheet" />


    </head>



    <body id="page-top">



        <!-- Navigation-->
        <nav class="navbar-fixed-top navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="#about">À propos</a></li>
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="#projects">Articles</a></li>
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="#signup">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <!--PERSONAL SCRIPT JavaScript-->
        <script type="text/javascript">
            $(function () {
                $(document).scroll(function () {
                    var $nav = $(".navbar-fixed-top");
                $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
        });
        });

        </script>

        <!-- Masthead-->
        <header class="masthead">

            <div class="container d-flex h-100 align-items-center">
                <div class="mx-auto text-center">
                    <h1 class="mx-auto my-0 text-uppercase">fangorn</h1>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5">Quelle forêt dans une France à +2° ?</h2>
                    <a class="btn btn-primary js-scroll-trigger" href="#about">Découvrir</a>
        


                </div>
            </div>
        </header>
        <!-- About-->
        <section class="about-section text-center" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h2 class="text-white mb-4">Pour une nouvelle alliance avec le bois !</h2>
                        <p class="text-white-50">
                            Les arbres sont de véritables alliées pour lutter contre le réchauffement climatique,
                            doper l'agriculture en refertilisant les sols, relancer la biodiversité, purifier l'air ou même fournir un matériau du futur. Le temps d'une nouvelle alliance avec eux est venu !
                        </p>
                    </div>
                </div>
                <%= link_to image_tag("niko-photos-tGTVxeOr_Rs-unsplash-removebg-preview.png"), root_path %>
            </div>
        </section>
        <!-- Projects-->
        <section class="projects-section bg-light" id="projects">
            <div class="container">

                <!-- Project One Row-->
                <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
                    <div class="col-lg-6"><img class="img-fluid" src="../abouttree.png" alt="" /></div>
                    <div class="col-lg-6">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    <h4>
                                    <%= link_to "Objectif : 1 Milliard", "/articles/new", class: "text-white" %></h4>
                                    <p class="mb-0 text-white-50">Planter 1 Milliard d'hectars d'arbres permettrait de retirer les deux tiers du CO2 rejetés dans l'atmosphère par l'homme. Comment atteindre un tel objectif ?</p>
                                    <hr class="d-none d-lg-block mb-0 ml-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project Two Row-->
                <div class="row justify-content-center no-gutters">
                   <div class="col-lg-6"><img class="img-fluid" src="../aboutt.jpg" alt="" /></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    <h4>
                                    <%= link_to "Pour sauver la planète, coupons des arbres !", "/blags/new", class: "text-white" %></h4>
                                    <p class="mb-0 text-white-50">Plaidoyer pour une mobilisation intelligente des ressources forestières.</p>
                                    <hr class="d-none d-lg-block mb-0 mr-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project three Row-->

                <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
                    <div class="col-lg-6"><img class="img-fluid" src="../sawing.jpg" alt="" /></div>
                    <div class="col-lg-6">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    <h4>
                                    <%= link_to "Scieries & première transformation", "/articles/show", class: "text-white" %></h4>
                                    <p class="mb-0 text-white-50">Déclin des scieries francaises : l'arbre qui cache la forêt ?</p>
                                    <hr class="d-none d-lg-block mb-0 ml-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project four Row-->
                <div class="row justify-content-center no-gutters">
                   <div class="col-lg-6"><img class="img-fluid" src="../builder.jpg" alt="" /></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    <h4>
                                    <%= link_to "La deuxième transformation & l'aval de la filière", "/blags/show", class: "text-white" %></h4>
                                    <p class="mb-0 text-white-50">Les industries de seconde transformation du bois dans la tourmente.</p>
                                    <hr class="d-none d-lg-block mb-0 mr-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


        </section>

        <!-- Signup-->
        <section class="signup-section" id="signup">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-lg-8 mx-auto text-center">
                        <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                        <h2 class="text-white mb-5">Ne ratez pas notre prochain article ! Abonnez-vous à notre newsletter :</h2>

                        <form action= <%= usercrea_path %> method="POST" class="form-inline d-flex">
                            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                            <input class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" name="gossip_text" type="email" placeholder="Entrez votre adresse mail..." />
                            <button class="btn btn-primary mx-auto" type="submit">S'inscrire</button>
                        </form>

                    </div>
                </div>
            </div>
        </section>
        <!-- Contact-->
        <section class="contact-section bg-black">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Adresse</h4>
                                <hr class="my-4" />
                                <div class="small text-black-50">76 rue Jouffroy d'Abbans, Paris, France</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-envelope text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Email</h4>
                                <hr class="my-4" />
                                <div class="small text-black-50"><a href="aimerycayol@gmail.com">projetfangorn@gmail.com</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-mobile-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Téléphone</h4>
                                <hr class="my-4" />
                                <div class="small text-black-50">+33665488525</div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container">Copyright © Fangorn</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Core theme JS-->
        <script src="app/assets/javascripts/material/scripts.js"></script>
    </body>
</html>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/blags/create.html.erb
<h1>Blags#create</h1>
<p>Find me in app/views/blags/create.html.erb</p>

app/views/blags/destroy.html.erb
<h1>Blags#destroy</h1>
<p>Find me in app/views/blags/destroy.html.erb</p>

app/views/blags/edit.html.erb
<h1>Blags#edit</h1>
<p>Find me in app/views/blags/edit.html.erb</p>

app/views/blags/index.html.erb
<h1>Blags#index</h1>
<p>Find me in app/views/blags/index.html.erb</p>

app/views/blags/update.html.erb
<h1>Blags#update</h1>
<p>Find me in app/views/blags/update.html.erb</p>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<ul>
  <% if user_signed_in? %>
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<ul>
  <% if user_signed_in? %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>



        <div id="index-gallery">
            <div class="itemi">
                <img src="aimery_copie.png" class="rounded-circle float-left">
            </div>

            <div class="itemi">
                <img src="aimery_copie.png" class="rounded-circle float-right">
            </div>
        </div>


  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/posts/_form.html.erb
<div class="container text-center mb-5">
  <br><br><br>
<%= form_with(model: post, local: true) do |form| %>
 <h1 class="h3 mb-3 font-weight-normal text-success">Publier un article</h1>
    <div class= "mb-3 mt-3 shadow p-3 mb-5 bg-white rounded">
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_area :title, class: "form-control h-63" %>
  </div>
<br>
  <div class="mb-6">
    <%= form.label :sous_titre %>
    <%= form.text_area :media, class: "form-control h-63" %>
  </div>
<br>
  <div class="mb-6">
    <%= form.label :contenu %>
    <%= form.text_area :body, class: "form-control h-64" %>
  </div>
<br>
  <div class="mb-6">
    <%= form.label :auteur %>
    <%= form.text_area :author, class: "form-control h-63" %>
  </div>
<br><br>
  <div class="field">
    <%= form.label :image_pour_la_page_accueil %>
    <%= form.file_field :image %>
  </div>
<br>
  <div class="actions">
    <%= form.submit class: "btn btn-default"%>
  </div>
    </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Author</th>
      <th>Media</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.author %></td>
        <td><%= post.media %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<ul>
  <% if admin_signed_in? %>
<%= render 'form', post: @post %>

<%= link_to 'Back', root_path %>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>
    

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en">


    <head>


        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">



        <title>Athanor</title>
        <link rel="icon" type="image/x-icon" href="/Users/aimery/Desktop/THP/J5/good/assets/img/Iconsmind-Outline-Tree-22.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->

        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/stylesheets/application.scss" rel="stylesheet" />


    </head>



    <body id="page-top">



        <!-- Navigation-->
        <nav class="navbar-fixed-top navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="/">À propos</a></li>
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="/#projects">Articles</a></li>
                        <li class="nav-item"><a class="centrenav nav-link js-scroll-trigger" href="/#signup">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <!--PERSONAL SCRIPT JavaScript-->
        <script type="text/javascript">
            $(function () {
                $(document).scroll(function () {
                    var $nav = $(".navbar-fixed-top");
                $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
        });
        });

        </script>

        <!-- Masthead-->
        <header class="masthead">
            <div class="container d-flex h-100 align-items-center">
                <div class="mx-auto text-center">
                    

                    <h2 class="text-white-50" style="font-size:40px"><%= @post.title %></h2>
                </div>
            </div>
        </header>


          <section class="projects-section bg-light" id="projects">
            <div class="container">
                <!-- Featured Project Row-->
                <div class="row align-items-center no-gutters mb-4 mb-lg-5">
                    <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src="brouillard.jpg" alt="" /></div>
                        <div class="featured-text text-center text-lg-left">

                        <p>  <%= markdown(@post.body) %> </p>

                        </div>
                    </div>
                </div>











        <!-- Footer-->


        <footer class="footer bg-black small text-center text-white-50">
            <%= link_to edit_post_path(@post) do %>
                <div class="container" >Copyright © Fangorn</div>
            <% end %>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Core theme JS-->
        <script src="app/assets/javascripts/material/scripts.js"></script>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>